version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: blogapi_2ge8
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: 0QyfSUPcO6kpq9ya5HkTLeWqz7mJaqwy
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/001-create-database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  blog-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://blog_user:0QyfSUPcO6kpq9ya5HkTLeWqz7mJaqwy@dpg-d1c1k83e5dus73f3h6eg-a.oregon-postgres.render.com/blogapi_2ge8
    depends_on:
      - postgres
    volumes:
      - ./uploads:/root/uploads
    restart: unless-stopped

volumes:
  postgres_data:
